name: instant_heat
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.5
  google_fonts: ^2.0.0-nullsafety.0
  context_holder: ^0.0.5
  syncfusion_flutter_sliders: ^20.1.50
  connectivity_plus: ^2.3.0
  network_info_plus: ^2.1.3
  firebase_storage: ^10.2.14
  firebase_core: ^1.15.0
  firebase_database: ^9.0.12
  cloud_firestore: ^3.1.13
  twilio_flutter: ^0.0.9
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/coffe1.png
    - images/coffe2.png
    - images/coffe3.png
    - images/ideal.png
    - images/connection.png


flutter_native_splash:
  background_image: "images/background.png"
  image: images/logo.png


